# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetsky.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetSky(object):
    def setupUi(self, WidgetSky):
        WidgetSky.setObjectName("WidgetSky")
        WidgetSky.resize(255, 188)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetSky)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(WidgetSky)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.spinBrightness = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBrightness.setProperty("value", 19.0)
        self.spinBrightness.setObjectName("spinBrightness")
        self.gridLayout.addWidget(self.spinBrightness, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 0, 1, 1)
        self.spinSeeing = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinSeeing.setSingleStep(0.1)
        self.spinSeeing.setProperty("value", 1.0)
        self.spinSeeing.setObjectName("spinSeeing")
        self.gridLayout.addWidget(self.spinSeeing, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 0, 1, 1)
        self.spinAirmass = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinAirmass.setProperty("value", 2.0)
        self.spinAirmass.setObjectName("spinAirmass")
        self.gridLayout.addWidget(self.spinAirmass, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 0, 1, 1)
        self.spinExtinction = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinExtinction.setSingleStep(0.1)
        self.spinExtinction.setProperty("value", 0.2)
        self.spinExtinction.setObjectName("spinExtinction")
        self.gridLayout.addWidget(self.spinExtinction, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(WidgetSky)
        QtCore.QMetaObject.connectSlotsByName(WidgetSky)

    def retranslateUi(self, WidgetSky):
        _translate = QtCore.QCoreApplication.translate
        WidgetSky.setWindowTitle(_translate("WidgetSky", "Form"))
        self.groupBox.setTitle(_translate("WidgetSky", "Sky"))
        self.label_23.setText(_translate("WidgetSky", "Brightness:"))
        self.spinBrightness.setSuffix(_translate("WidgetSky", " mag/as²"))
        self.label_24.setText(_translate("WidgetSky", "Seeing:"))
        self.spinSeeing.setSuffix(_translate("WidgetSky", " \""))
        self.label_25.setText(_translate("WidgetSky", "Airmass:"))
        self.label_26.setText(_translate("WidgetSky", "Extinction:"))
        self.spinExtinction.setSuffix(_translate("WidgetSky", " mag/am"))
