# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgettarget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetTarget(object):
    def setupUi(self, WidgetTarget):
        WidgetTarget.setObjectName("WidgetTarget")
        WidgetTarget.resize(207, 192)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetTarget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(WidgetTarget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboType = QtWidgets.QComboBox(self.groupBox)
        self.comboType.setObjectName("comboType")
        self.comboType.addItem("")
        self.gridLayout.addWidget(self.comboType, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboTemplate = QtWidgets.QComboBox(self.page)
        self.comboTemplate.setObjectName("comboTemplate")
        self.gridLayout_2.addWidget(self.comboTemplate, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBrightness = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBrightness.setMinimum(-99.99)
        self.spinBrightness.setProperty("value", 15.0)
        self.spinBrightness.setObjectName("spinBrightness")
        self.gridLayout_3.addWidget(self.spinBrightness, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboFilter = QtWidgets.QComboBox(self.groupBox)
        self.comboFilter.setObjectName("comboFilter")
        self.gridLayout_3.addWidget(self.comboFilter, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(WidgetTarget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetTarget)

    def retranslateUi(self, WidgetTarget):
        _translate = QtCore.QCoreApplication.translate
        WidgetTarget.setWindowTitle(_translate("WidgetTarget", "Form"))
        self.groupBox.setTitle(_translate("WidgetTarget", "Target"))
        self.label.setText(_translate("WidgetTarget", "Type:"))
        self.comboType.setItemText(0, _translate("WidgetTarget", "Template"))
        self.label_2.setText(_translate("WidgetTarget", "Name:"))
        self.label_3.setText(_translate("WidgetTarget", "Brigthness:"))
        self.spinBrightness.setSuffix(_translate("WidgetTarget", " mag"))
        self.label_4.setText(_translate("WidgetTarget", "Filter:"))
